# Site settings
title: "Zenon.fun"
email: cryptovagrant@pm.me
description: "A place to host interesting and fun Zenon projects."
baseurl: ""
url: "http://www.zenon.fun/"
title_description: "A place to host interesting and fun Zenon projects."
title_image: "./img/zenon.jpg"
#google_analytics: "UA-20365477-4"
#disqus_account: 
github_repository: 
#addthis_id: ra-513c6fa83da6ec67
#post_limit: 5

# Social usernames/URLs
twitter_username:
github_username:  
instagram_username: 
reddit_username: 
linkedin_link:
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/Sol-Sanctum\">Sol Sanctum</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Sol-Sanctum/sol-sanctum.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
